[colors]
foreground = "white"
background = "black"
accent = "cyan"
visualizer_foreground = "Lightblue"
visualizer_background = "black"

[keybinds]
quit = "q"
play_pause = "space"
next = "n"
previous = "p"
shuffle = "s"
volume_up = "+"
volume_down = "-"
select = "enter"
clear = "c"
seek_forward = "l"
seek_backward = "h"
help = "?"

[visualizer]
bar_count = 50
smoothing = 0.699999988079071
